
import { Inter } from "next/font/google";
import Image from "next/image";
import logo from "../../public/asset/images/logo.svg";
import Link from "next/link";
import "./globals.css";
import navbar from "./components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <div className="bg-[#F9FCFF]">
                    <nav className="max-w-7xl mx-auto flex justify-between ">
                        <div>
                            <Image src={logo} alt="logo" />
                        </div>
                        <div>
                            <ul className="flex gap-4">
                                <li className="cursor-pointer">
                                    <Link href="/">Home</Link>
                                </li>
                                <li>
                                    <Link href="/about">About</Link>
                                </li>
                            </ul>
                            <navbar />
                        </div>
                    </nav>
                </div>

                {children}
                <footer>
                    <h2>footer</h2>
                </footer>
            </body>
        </html>
    );
}
