import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import StoreProvider from "@/provider/provider"


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Ehya Blog Website",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
               <StoreProvider>
               <Navbar />
                    {children}
                    <Footer />
               </StoreProvider>
                    
                
            </body>
        </html>
    );
}
